version: '3.8'

services:
  db:
    image: postgres:14.15
    container_name: my_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${PASSPOSTGRES}
    ports:
      - "5431:5432"
    env_file:
      - .env

  datafeed:
    build:
      context: .
      dockerfile: ./process_data/Dockerfile
    network_mode: "host"
    env_file:
      - .env
    volumes:
      - .:/home/project_root
    command: python -m process_data

  webapp:
    build:
      context: .
      dockerfile: ./web_app/Dockerfile
    network_mode: "host"
    env_file:
      - .env
    volumes:
      - .:/home/web_app_project_root
    command: python -m web_app
